name: myapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^0.8.6+1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2  # Pastikan menggunakan versi terbaru jika tersedia

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"  # Pastikan path benar
  adaptive_icon_background: "#ffffff"  # Background ikon adaptif (khusus Android)
  adaptive_icon_foreground: "assets/logo.png"  # Foreground ikon adaptif (khusus Android)

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
