name: myapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^0.8.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2 # Menambahkan flutter_launcher_icons untuk logo aplikasi

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # Lokasi file logo baru

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
